version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: node-backend
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: always
    command: ["npm", "run", "migrate-and-start"]

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: next-frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
    command: ["npm", "run", "start"]

volumes:
  mysqldata:
